<?php

use MrEssex\CubexSkeleton\Ui\Layout\DefaultLayout\DefaultLayout;
use Packaged\Dispatch\ResourceStore;

/**
 * @var DefaultLayout $this
 */

?>

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <?= $this->dispatch->store()->generateHtmlIncludes() ?>
</head>
<body>
<main id="main">
  <?= $this->getContent() ?>
</main>
<?= $this->dispatch->store()->generateHtmlIncludes(ResourceStore::TYPE_JS) ?>
</body>
</html>
