<?php

use MrEssex\CubexSkeleton\System\Layout\LayoutWrap\LayoutWrap;
use Packaged\Dispatch\ResourceStore;

/**
 * @var LayoutWrap $this
 */
?>

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <meta name="favicon" content="/favicon.ico?v=1">
  <title>Document</title>
  <?= $this->dispatch->store()->generateHtmlIncludes() ?>
</head>
<body>
<?= $this->getContent() ?>
<?= $this->dispatch->store()->generateHtmlIncludes(ResourceStore::TYPE_JS) ?>
</body>
</html>
